import { Pressable, StyleSheet, Text, View } from 'react-native';
import { brand, radius, space, type } from '../../design';
import { compactCopy, CONTENT_LIMITS } from '../../stardust-feed';
import OrbitDot from './OrbitDot';

export default function ForecastCard({ night, prompt, status, actionLabel = 'Enter tonight’s ritual', onPress }: { night: number; prompt: string; status: string; actionLabel?: string; onPress: () => void }) {
  return <Pressable onPress={onPress} accessibilityRole="button" accessibilityLabel={`Night ${night} forecast. ${prompt}`} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.topline}><Text style={styles.eyebrow}>NIGHT {String(night).padStart(2, '0')} FORECAST</Text><View style={styles.pill}><Text style={styles.pillText}>{status}</Text></View></View><View style={styles.visual}><View style={[styles.star, styles.starOne]} /><View style={[styles.star, styles.starTwo]} /><OrbitDot /><View style={styles.moon} /></View><Text style={styles.title}>{compactCopy(prompt, CONTENT_LIMITS.forecastBody)}</Text><View style={styles.actionRow}><Text style={styles.action}>{actionLabel}</Text><Text style={styles.arrow}>→</Text></View></Pressable>;
}

const styles = StyleSheet.create({
  card: { marginTop: space.lg, minHeight: 340, padding: space.lg, borderRadius: radius.xl, backgroundColor: brand.card, borderWidth: 1, borderColor: 'rgba(235,180,194,0.32)', justifyContent: 'space-between', overflow: 'hidden' }, topline: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', zIndex: 2 }, eyebrow: { ...type.eyebrow, color: brand.rose, fontSize: 9, lineHeight: 12, letterSpacing: 1.4 }, pill: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: radius.pill, backgroundColor: 'rgba(236,200,133,0.10)', borderWidth: 1, borderColor: 'rgba(236,200,133,0.30)' }, pillText: { ...type.eyebrow, color: brand.gold, fontSize: 8 }, visual: { height: 170, alignItems: 'center', justifyContent: 'center' }, moon: { position: 'absolute', width: 68, height: 68, borderRadius: 34, backgroundColor: brand.purple, borderWidth: 1, borderColor: 'rgba(239,234,255,0.18)', shadowColor: brand.purple, shadowOpacity: 0.42, shadowRadius: 24 }, star: { position: 'absolute', width: 3, height: 3, borderRadius: 2, backgroundColor: brand.ink, opacity: 0.54 }, starOne: { left: '18%', top: '22%' }, starTwo: { right: '18%', bottom: '22%' }, title: { ...type.bodyStrong, color: brand.ink, fontSize: 20, lineHeight: 27, maxWidth: 320 }, actionRow: { marginTop: space.lg, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, action: { ...type.bodyStrong, color: brand.ink, fontSize: 12 }, arrow: { color: brand.gold, fontSize: 19 }, pressed: { opacity: 0.78, transform: [{ scale: 0.99 }] },
});
