import { Pressable, StyleSheet, Text, View } from 'react-native';
import { phaseForNight } from '../../stardust-feed';
import { brand, radius, space, type } from '../../design';

export default function PhaseVisualization({ night, completed, onPress }: { night: number; completed: number; onPress: () => void }) {
  const phase = phaseForNight(night);
  return <Pressable onPress={onPress} accessibilityRole="button" accessibilityLabel={`${phase.title}. Night ${night} of 21.`} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.visual}><View style={styles.ringOuter}><View style={styles.ringInner}><Text style={styles.number}>{String(night).padStart(2, '0')}</Text><Text style={styles.of}>OF 21</Text></View></View>{Array.from({ length: 12 }, (_, index) => <View key={index} style={[styles.star, { transform: [{ rotate: `${index * 30}deg` }, { translateY: -86 }], opacity: index < Math.ceil((night / 21) * 12) ? 1 : 0.2 }]} />)}</View><Text style={styles.kicker}>{phase.label}</Text><Text style={styles.title}>{phase.title}</Text><Text style={styles.body}>{completed} sealed {completed === 1 ? 'night' : 'nights'} form the visible path. Private text never enters this view.</Text><Text style={styles.action}>Explore the journey →</Text></Pressable>;
}
const styles = StyleSheet.create({ card: { marginTop: space.lg, minHeight: 400, padding: space.lg, borderRadius: radius.xl, backgroundColor: brand.sky, borderWidth: 1, borderColor: 'rgba(137,108,181,0.38)' }, visual: { height: 220, alignItems: 'center', justifyContent: 'center' }, ringOuter: { width: 174, height: 174, borderRadius: 87, borderWidth: 1, borderColor: brand.purple, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(137,108,181,0.08)' }, ringInner: { width: 118, height: 118, borderRadius: 59, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(235,180,194,0.12)', borderWidth: 1, borderColor: 'rgba(235,180,194,0.30)' }, number: { ...type.display, color: brand.ink, fontSize: 42, lineHeight: 46 }, of: { ...type.eyebrow, color: brand.inkMid, fontSize: 8 }, star: { position: 'absolute', width: 6, height: 6, borderRadius: 3, backgroundColor: brand.gold }, kicker: { ...type.eyebrow, color: brand.gold, fontSize: 9, lineHeight: 12 }, title: { ...type.bodyStrong, color: brand.ink, fontSize: 20, lineHeight: 26, marginTop: 3 }, body: { ...type.body, color: brand.inkMid, fontSize: 13, lineHeight: 19, marginTop: space.sm }, action: { ...type.bodyStrong, color: brand.rose, fontSize: 12, marginTop: space.lg }, pressed: { opacity: 0.78, transform: [{ scale: 0.99 }] } });
