import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { FeedTag } from '../../stardust-feed';
import { brand, radius, space, type } from '../../design';

const TONES = { rose: brand.rose, gold: brand.gold, purple: brand.purple };
export default function TagGrid({ tags, selected, onToggle, onAddMore, showAddMore = true }: { tags: FeedTag[]; selected: string[]; onToggle: (id: string) => void; onAddMore: () => void; showAddMore?: boolean }) {
  return <View style={styles.grid}>{tags.map((tag) => { const active = selected.includes(tag.id); const color = TONES[tag.tone]; return <Pressable key={tag.id} onPress={() => onToggle(tag.id)} accessibilityRole="checkbox" accessibilityState={{ checked: active }} accessibilityLabel={`${tag.label}, intensity ${tag.intensity}, ${active ? 'selected' : 'not selected'}`} style={({ pressed }) => [styles.tag, active && { borderColor: color, backgroundColor: `${color}20` }, pressed && styles.pressed]}><View style={[styles.intensity, { backgroundColor: color, opacity: 0.45 + tag.intensity * 0.18 }]} /><Text style={[styles.label, active && styles.activeLabel]}>{tag.label}</Text></Pressable>; })}{showAddMore ? <Pressable onPress={onAddMore} accessibilityRole="button" accessibilityLabel="Add more feelings" style={({ pressed }) => [styles.tag, styles.more, pressed && styles.pressed]}><Text style={styles.moreLabel}>+ add more</Text></Pressable> : null}</View>;
}
const styles = StyleSheet.create({ grid: { flexDirection: 'row', flexWrap: 'wrap', gap: space.sm, marginTop: space.lg }, tag: { minHeight: 42, paddingHorizontal: space.md, borderRadius: radius.pill, borderWidth: 1, borderColor: brand.line, backgroundColor: brand.card, flexDirection: 'row', alignItems: 'center' }, intensity: { width: 8, height: 8, borderRadius: 4, marginRight: space.sm }, label: { ...type.label, fontSize: 12, lineHeight: 15, color: brand.inkMid }, activeLabel: { color: brand.ink }, more: { borderStyle: 'dashed' }, moreLabel: { ...type.label, fontSize: 12, color: brand.gold }, pressed: { opacity: 0.72, transform: [{ scale: 0.97 }] } });
